version: '3'

services:
  db:
    image: mongodb
    ports:
        - "27017":"27017"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
